remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one # add this line to the plugins list if you already have one
title: "Leuck Family Reunion"
description: "June 26 to July 1 2023"
gitorg: "https://github.com/jm1021/leuck_reunion"
google_analytics:
title: The Opps Daily
description: NFL statics and data for dummies. 
